controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api:
    resource: '../src/Controller/'
    type: attribute
    prefix: /api
    name_prefix: 'api_'
